fix color depth loss during repetitive drawing increase bitrate to 10Mbps reduce framerate to 5fps add x264 file

diff --git a/prepareraw b/prepareraw
--- a/prepareraw
+++ b/prepareraw
@@ -10,12 +10,15 @@
 ##############################################
 
 
+x265="./x26510bit"
+x264="x264"
+
 # check dependencies
 hash convert 2>/dev/null || { echo >&2 "This script requires ImageMagic but it's not installed.  Aborting."; exit 1; }
 hash ffmpeg 2>/dev/null || { echo >&2 "This script requires ffmpeg but it's not installed.  Aborting."; exit 1; }
-ffmpeg -pix_fmts 2>&1 |grep yuv420p10 >/dev/null || { echo >&2 "It seems to me, that ffmpeg was not built with 10bit support.  Aborting."; exit 1; }
-hash x265 2>/dev/null || { echo >&2 "This script requires x256 but it's not installed. You can download it from http://x265.org. Please make sure, you build it with 10bit support! Aborting."; exit 1; }
-x265 --version 2>&1 |grep "build" |grep 10bit >/dev/null || { echo >&2 "It seems to me, that x265 was not built with 10bit support! Aborting. (see https://bitbucket.org/multicoreware/x265/wiki/Home)"; exit 1; }
+ffmpeg -pix_fmts 2>&1 |grep yuv444p10 >/dev/null || { echo >&2 "It seems to me, that ffmpeg was not built with 10bit support.  Aborting."; exit 1; }
+hash $x265 2>/dev/null || { echo >&2 "This script requires x256 but it's not installed. You can download it from http://x265.org. Please make sure, you build it with 10bit support! Aborting."; exit 1; }
+$x265 --version 2>&1 |grep "build" |grep 10bit >/dev/null || { echo >&2 "It seems to me, that x265 was not built with 10bit support! Aborting. (see https://bitbucket.org/multicoreware/x265/wiki/Home)"; exit 1; }
 hash MP4Box 2>/dev/null || { echo >&2 "This script requires GPAC but it's not installed. Aborting."; exit 1; }
 
 # check TMPDIR
@@ -35,7 +38,7 @@ else
   height=216
 
   echo "creating blue 8 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 255); do
     color=$(printf "#%04x%04xffff" $(($i * 256)) $(($i * 256)) )
     x1=$(($i * 15))
@@ -50,7 +53,7 @@ else
   eval  $command
 
   echo "creating blue 10 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 1023); do
     color=$(printf "#%04x%04xffff" $(($i * 64)) $(($i * 64)) )
     x1=$(printf "%.0f" $(echo "$i * 3.75" |bc))
@@ -64,7 +67,7 @@ else
   command=$command"gradient.png"
   eval  $command
 
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 1023); do
     x1=$(printf "%.0f" $(echo "$i * 3.75" |bc))
     y1=$(($height * 1 + 1))
@@ -79,7 +82,7 @@ else
 
 
   echo "creating green 8 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 255); do
     color=$(printf "#%04xffff%04x" $(($i * 256)) $(($i * 256)) )
     x1=$(($i * 15))
@@ -94,7 +97,7 @@ else
   eval  $command
 
   echo "creating green 10 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 1023); do
     color=$(printf "#%04xffff%04x" $(($i * 64)) $(($i * 64)) )
     x1=$(printf "%.0f" $(echo "$i * 3.75" |bc))
@@ -108,7 +111,7 @@ else
   command=$command"gradient.png"
   eval  $command
 
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 1023); do
     x1=$(printf "%.0f" $(echo "$i * 3.75" |bc))
     y1=$(($height * 3 + 1))
@@ -122,7 +125,7 @@ else
 
 
   echo "creating red 8 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 255); do
     color=$(printf "#ffff%04x%04x" $(($i * 256)) $(($i * 256)) )
     x1=$(($i * 15))
@@ -137,7 +140,7 @@ else
   eval  $command
 
   echo "creating red 10 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 1023); do
     color=$(printf "#ffff%04x%04x" $(($i * 64)) $(($i * 64)) )
     x1=$(printf "%.0f" $(echo "$i * 3.75" |bc))
@@ -151,7 +154,7 @@ else
   command=$command"gradient.png"
   eval  $command
 
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 1023); do
     x1=$(printf "%.0f" $(echo "$i * 3.75" |bc))
     y1=$(($height * 5 + 1))
@@ -166,7 +169,7 @@ else
 
 
   echo "creating gray 8 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 255); do
     color=$(printf "#%04x%04x%04x" $(($i * 256)) $(($i * 256)) $(($i * 256)) )
     x1=$(($i * 15))
@@ -181,7 +184,7 @@ else
   eval  $command
 
   echo "creating gray 10 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 1023); do
     color=$(printf "#%04x%04x%04x" $(($i * 64)) $(($i * 64)) $(($i * 64)) )
     x1=$(printf "%.0f" $(echo "$i * 3.75" |bc))
@@ -195,7 +198,7 @@ else
   command=$command"gradient.png"
   eval  $command
 
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for i in $(seq 0 1023); do
     x1=$(printf "%.0f" $(echo "$i * 3.75" |bc))
     y1=$(($height * 7 + 1))
@@ -210,7 +213,7 @@ else
 
 
   echo "creating gray 8 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for j in $(seq 128 191); do
     color=$(printf "#%04x%04x%04x" $(($j * 256)) $(($j * 256)) $(($j * 256)) )
     i=$(($j - 128))
@@ -226,7 +229,7 @@ else
   eval  $command
 
   echo "creating gray 10 bit gradient"
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for j in $(seq 512 767); do
     color=$(printf "#%04x%04x%04x" $(($j * 64)) $(($j * 64)) $(($j * 64)) )
     i=$(($j - 512))
@@ -241,7 +244,7 @@ else
   command=$command"gradient.png"
   eval  $command
 
-  command="convert gradient.png "
+  command="convert -depth 16 gradient.png "
   for j in $(seq 512 767); do
     i=$(($j - 512))
     x1=$(($i * 15))
@@ -256,7 +259,7 @@ else
 
 
 
-  convert gradient.png -fill "#ffffffffffff" -pointsize 16 -gravity SouthEast -annotate +0+30 'gradient v1.1 - http://jursonovics.com - This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.' gradient.png
+  convert -depth 16 gradient.png -fill "#ffffffffffff" -pointsize 16 -gravity SouthEast -annotate +0+30 'gradient v1.1 - http://jursonovics.com - This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.' gradient.png
 
 fi
 
@@ -265,9 +268,21 @@ fi
 if [ ! -f gradient.mp4 ]; then
 
   echo "converting png to h265 raw video file"
-  ffmpeg -y -loop 1 -t 10 -framerate 50 -i gradient.png -f yuv4mpegpipe -pix_fmt yuv420p10 -strict -1 - | x265 --y4m --bitrate 3000 -o $TMPDIR/gradient.265 -
+  ffmpeg -y -loop 1 -t 10 -framerate 5 -i gradient.png -f yuv4mpegpipe -pix_fmt yuv420p10 -strict -1 - | $x265 --y4m --preset veryslow --bitrate 10000 -o $TMPDIR/gradient.265 -
 
   echo "packaging h265 file"
   MP4Box -add $TMPDIR/gradient.265 gradient.mp4
 fi
+
+# encode and package video with x264 10-bit support...
+if [ ! -f gradient_x264.mp4 ]; then
+
+  echo "converting png to h264 raw video file"
+  ffmpeg -y -loop 1 -t 10 -framerate 5 -i gradient.png -f yuv4mpegpipe -pix_fmt yuv420p10 -strict -1 - | $x264 --preset veryslow --bitrate 10000 -o $TMPDIR/gradient.264 dev/stdin
+
+  echo "packaging h264 file"
+  MP4Box -add $TMPDIR/gradient.265 gradient_x264.mp4
+fi
+
+
 
